services:
  - type: web
    name: tennis-booking-bot
    env: node
    buildCommand: npm install && npx playwright install chromium && npx playwright install-deps chromium
    startCommand: NODE_ENV=production tsx server/index.ts
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: REC_US_EMAIL
        fromSecret: REC_US_EMAIL
      - key: REC_US_PASSWORD
        fromSecret: REC_US_PASSWORD
      - key: TWILIO_ACCOUNT_SID
        fromSecret: TWILIO_ACCOUNT_SID
      - key: TWILIO_AUTH_TOKEN
        fromSecret: TWILIO_AUTH_TOKEN
      - key: TWILIO_PHONE_NUMBER
        fromSecret: TWILIO_PHONE_NUMBER